### ISSUE TITLE
'title_english' missing in Manga Interface

### ISSUE THREAD

**Issue by Daniel2193** [tutkli/jikan-ts#10]
The Manga Interface (`src/models/Manga/manga.model.ts`) does not contain a `title_english` field.

Another thing I noticed is that the `title_english` field on the Anime Interface (`src/models/Anime/anime.model.ts`) is typed as `string`. The API might return `null` for both Anime and Manga on the `title_english` field.

**Comment by tutkli** [comment]
Hi, @Daniel2193 ! I fixed title_english for anime and manga models. It's available in v2.0.2
