### ISSUE TITLE
getAnimeRelations and other missing endpoints

### ISSUE THREAD

**Issue by HugoLeBoennec** [tutkli/jikan-ts#6]
Hello,

I see 100% coverage, but I think is not clear, or it is missing **AnimeRelations**, and some others...

thx for the work already done 👍

**Comment by tutkli** [comment]
Hello. The coverage represents the tests percentage of the current endpoints, sorry for the confusion. 
I will look into implementing the missing endpoints.

**Comment by tutkli** [comment]
Hello @HugoLeBoennec sorry for the long wait. I just updated the Anime client with a few more endpoint, including `getAnimeRelations`.  Should be available in version 1.2.0

**Comment by tutkli** [comment]
Hi @HugoLeBoennec sorry for the lateness. This is available in version 2.1.0 :)
